import Head from "next/head";
import { Poppins } from "@next/font/google";
import Homee from "@/components/main/Homee";
import { db, initFirebase } from "@/firebase/FirebaseApp";
import { useAuthState } from "react-firebase-hooks/auth";

import { getAuth } from "firebase/auth";
import { useMode } from "@/components/useHooks/useMode";
const poppins = Poppins({ subsets: ["latin"],weight: ['400','700'] });
// remove
export default function Home() {
    const {mode}=useMode();
  const auth = getAuth();

const app=initFirebase();
const [user]=useAuthState(auth)


  return (
    <div className="flex flex-col items-center">
  <div>
  <Head>
        <title >Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={` ${mode?'bg-[#1b2430] text-[#E7F6F2]':'bg-[#EBEBEB]'} mx-auto flex items-center justify-center  `}>





<Homee/>


<div className="fixed   top-1/2">
</div>
      </div>
 </div> 

   
    
    </div>
  );
}
